# Generated by Django 5.0.1 on 2024-01-24 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="business_query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("contact_person", models.CharField(max_length=50)),
                ("street_address", models.CharField(max_length=255)),
                ("street_address_line_2", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=50)),
                ("postal_code", models.IntegerField()),
                ("country", models.CharField(max_length=50)),
                ("ph_no", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("details", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="contact_query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="dealer_request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("companyname", models.CharField(max_length=50)),
                ("add_line_1", models.CharField(max_length=255)),
                ("add_line_2", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("postalcode", models.IntegerField()),
                ("ph_no", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("wh_city", models.CharField(max_length=50)),
                ("wh_area", models.CharField(max_length=255)),
                ("wh_country", models.CharField(max_length=50)),
                ("wh_tenure", models.CharField(max_length=50)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="dealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("pincode", models.IntegerField()),
                ("country", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.BigIntegerField()),
                ("add_line_1", models.CharField(max_length=255)),
                ("add_line_2", models.CharField(max_length=255)),
                ("jdate", models.DateField()),
                (
                    "dealer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order_shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_id", models.IntegerField()),
                ("n_sender_add", models.CharField(max_length=50)),
                ("n_sender_zip", models.IntegerField()),
                ("n_sender_city", models.CharField(max_length=50)),
                ("n_sender_country", models.CharField(max_length=50)),
                ("n_sender_ph_no", models.BigIntegerField()),
                ("n_recipent", models.CharField(max_length=50)),
                ("n_recipent_add", models.CharField(max_length=50)),
                ("n_recipent_zip", models.IntegerField()),
                ("n_recipent_city", models.CharField(max_length=50)),
                ("n_recipent_country", models.CharField(max_length=50)),
                ("n_recipent_ph_no", models.BigIntegerField()),
                ("p_width", models.FloatField()),
                ("p_length", models.FloatField()),
                ("p_height", models.FloatField()),
                ("p_weight", models.FloatField()),
                ("p_type", models.CharField(max_length=50)),
                ("p_insurance", models.CharField(max_length=50)),
                ("p_fragile", models.CharField(max_length=50)),
                (
                    "shipment_status",
                    models.CharField(
                        choices=[
                            ("1", "assigned"),
                            ("2", "pickup"),
                            ("3", "at sender office"),
                            ("4", "onboard"),
                            ("5", "at receiver office"),
                            ("6", "deliver"),
                            ("7", "end"),
                        ],
                        default="start",
                        max_length=50,
                    ),
                ),
                ("cost", models.FloatField()),
                ("distance", models.FloatField()),
                ("mot", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("e_date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "r_dealer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="r_dealer",
                        to="fastbox_app.dealer",
                    ),
                ),
                (
                    "s_dealer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="s_dealer",
                        to="fastbox_app.dealer",
                    ),
                ),
                (
                    "sender_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                (
                    "dealer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fastbox_app.dealer",
                    ),
                ),
                (
                    "assigned_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fastbox_app.order_shipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="userProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="images"),
                ),
                ("address", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=50)),
                ("ph_no", models.BigIntegerField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        db_column="userID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
