# Generated by Django 5.0.1 on 2024-01-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fastbox_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_shipment",
            name="e_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
