# Generated by Django 5.0.1 on 2024-01-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fastbox_app", "0002_alter_order_shipment_e_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="e_email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="e_phone",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
