# Generated by Django 5.0.1 on 2024-02-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fastbox_app", "0003_employee_e_email_employee_e_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_shipment",
            name="mot",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
