# Generated by Django 5.0.1 on 2024-02-14 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fastbox_app", "0004_alter_order_shipment_mot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order_shipment",
            old_name="p_fragile",
            new_name="p_size",
        ),
        migrations.RemoveField(
            model_name="order_shipment",
            name="p_height",
        ),
        migrations.RemoveField(
            model_name="order_shipment",
            name="p_length",
        ),
        migrations.RemoveField(
            model_name="order_shipment",
            name="p_width",
        ),
    ]
