# Generated by Django 5.0.1 on 2024-02-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fastbox_app", "0005_rename_p_fragile_order_shipment_p_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="assigned_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="fastbox_app.order_shipment",
            ),
        ),
    ]
