# Generated by Django 5.0.1 on 2024-02-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fastbox_app", "0006_alter_employee_assigned_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="assigned_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="fastbox_app.order_shipment",
            ),
        ),
    ]
